/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controlador.ControladorSistema;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.WindowConstants;

/**
 *
 * @author VICTOR
 */
public class VistaSistema extends javax.swing.JFrame {

    /**
     * Creates new form VistaSistema
     */
    public VistaSistema() {
        initComponents();
        setCustomIcon();
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    }

    private void setCustomIcon() {
        // Cargar el icono desde el archivo .png en la carpeta 'img'
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/iconcerdo.png"));
        setIconImage(icon); // Establecer el icono de la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cn = new javax.swing.JPanel();
        lblSistemaTitulo = new javax.swing.JLabel();
        btnSistemaVentas = new javax.swing.JButton();
        btnSistemaUsusarios = new javax.swing.JButton();
        btnSistemaProductos = new javax.swing.JButton();
        btnSistemaBitacora = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSistemaClientes = new javax.swing.JButton();
        btnSistemaNuevaVenta = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuVentas = new javax.swing.JMenuItem();
        MenuProductos = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenuItem();
        menuBitacoras = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuCerrarS = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(193, 18, 31));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIENVENIDO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(323, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(257, 257, 257))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 0, 800, 110));

        cn.setBackground(new java.awt.Color(120, 0, 0));
        cn.setForeground(new java.awt.Color(120, 0, 0));

        lblSistemaTitulo.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        lblSistemaTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblSistemaTitulo.setText("Sistema");

        btnSistemaVentas.setBackground(new java.awt.Color(120, 0, 0));
        btnSistemaVentas.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        btnSistemaVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnSistemaVentas.setText("VENTAS");
        btnSistemaVentas.setBorder(null);
        btnSistemaVentas.setBorderPainted(false);
        btnSistemaVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSistemaVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaVentasActionPerformed(evt);
            }
        });

        btnSistemaUsusarios.setBackground(new java.awt.Color(120, 0, 0));
        btnSistemaUsusarios.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        btnSistemaUsusarios.setForeground(new java.awt.Color(255, 255, 255));
        btnSistemaUsusarios.setText("USUARIOS");
        btnSistemaUsusarios.setBorder(null);
        btnSistemaUsusarios.setBorderPainted(false);
        btnSistemaUsusarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSistemaUsusarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaUsusariosActionPerformed(evt);
            }
        });

        btnSistemaProductos.setBackground(new java.awt.Color(120, 0, 0));
        btnSistemaProductos.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        btnSistemaProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnSistemaProductos.setText("PRODUCTOS");
        btnSistemaProductos.setBorder(null);
        btnSistemaProductos.setBorderPainted(false);
        btnSistemaProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSistemaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaProductosActionPerformed(evt);
            }
        });

        btnSistemaBitacora.setBackground(new java.awt.Color(120, 0, 0));
        btnSistemaBitacora.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        btnSistemaBitacora.setForeground(new java.awt.Color(255, 255, 255));
        btnSistemaBitacora.setText("BITACORA");
        btnSistemaBitacora.setBorder(null);
        btnSistemaBitacora.setBorderPainted(false);
        btnSistemaBitacora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSistemaBitacora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaBitacoraActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogoC.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(160, 160));

        btnSistemaClientes.setBackground(new java.awt.Color(120, 0, 0));
        btnSistemaClientes.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        btnSistemaClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnSistemaClientes.setText("CLIENTES");
        btnSistemaClientes.setBorder(null);
        btnSistemaClientes.setBorderPainted(false);
        btnSistemaClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSistemaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaClientesActionPerformed(evt);
            }
        });

        btnSistemaNuevaVenta.setBackground(new java.awt.Color(120, 0, 0));
        btnSistemaNuevaVenta.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        btnSistemaNuevaVenta.setForeground(new java.awt.Color(255, 255, 255));
        btnSistemaNuevaVenta.setText("NUEVA VENTA");
        btnSistemaNuevaVenta.setBorder(null);
        btnSistemaNuevaVenta.setBorderPainted(false);
        btnSistemaNuevaVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSistemaNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaNuevaVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cnLayout = new javax.swing.GroupLayout(cn);
        cn.setLayout(cnLayout);
        cnLayout.setHorizontalGroup(
            cnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cnLayout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addComponent(lblSistemaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cnLayout.createSequentialGroup()
                .addGroup(cnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSistemaVentas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSistemaUsusarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSistemaBitacora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSistemaProductos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSistemaClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSistemaNuevaVenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        cnLayout.setVerticalGroup(
            cnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cnLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblSistemaTitulo)
                .addGap(18, 18, 18)
                .addComponent(btnSistemaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSistemaUsusarios, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSistemaBitacora, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSistemaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSistemaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSistemaNuevaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 749));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jMenu1.setText("Operaciones");

        menuVentas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuVentas.setText("Ventas");
        menuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVentasActionPerformed(evt);
            }
        });
        jMenu1.add(menuVentas);

        MenuProductos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuProductos.setText("Productos");
        MenuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProductosActionPerformed(evt);
            }
        });
        jMenu1.add(MenuProductos);

        menuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuUsuarios.setText("Usuarios");
        menuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(menuUsuarios);

        menuBitacoras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuBitacoras.setText("Bitacoras");
        menuBitacoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBitacorasActionPerformed(evt);
            }
        });
        jMenu1.add(menuBitacoras);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sesion");

        menuCerrarS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD9, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuCerrarS.setText("Cerrar Sesion");
        menuCerrarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCerrarSActionPerformed(evt);
            }
        });
        jMenu2.add(menuCerrarS);

        menuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD0, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenu2.add(menuSalir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSistemaBitacoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaBitacoraActionPerformed
        ControladorSistema.iniciarBitacora();
    }//GEN-LAST:event_btnSistemaBitacoraActionPerformed

    private void btnSistemaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaProductosActionPerformed
        ControladorSistema.iniciarProductos();
    }//GEN-LAST:event_btnSistemaProductosActionPerformed

    private void btnSistemaUsusariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaUsusariosActionPerformed
        ControladorSistema.iniciarUsuarios();
    }//GEN-LAST:event_btnSistemaUsusariosActionPerformed

    private void btnSistemaVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaVentasActionPerformed
        ControladorSistema.iniciarVentas();

    }//GEN-LAST:event_btnSistemaVentasActionPerformed

    private void btnSistemaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSistemaClientesActionPerformed

    private void btnSistemaNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaNuevaVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSistemaNuevaVentaActionPerformed

    private void MenuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProductosActionPerformed
        ControladorSistema.iniciarProductos();
    }//GEN-LAST:event_MenuProductosActionPerformed

    private void menuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuariosActionPerformed
        ControladorSistema.iniciarUsuarios();
    }//GEN-LAST:event_menuUsuariosActionPerformed

    private void menuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVentasActionPerformed
        ControladorSistema.iniciarVentas();
    }//GEN-LAST:event_menuVentasActionPerformed

    private void menuBitacorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBitacorasActionPerformed
        ControladorSistema.iniciarBitacora();
    }//GEN-LAST:event_menuBitacorasActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
      ControladorSistema.Salir();
    }//GEN-LAST:event_menuSalirActionPerformed
      
    private void menuCerrarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCerrarSActionPerformed
      ControladorSistema.cerrarSesion();

    }//GEN-LAST:event_menuCerrarSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaSistema().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuProductos;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnSistemaBitacora;
    private javax.swing.JButton btnSistemaClientes;
    private javax.swing.JButton btnSistemaNuevaVenta;
    private javax.swing.JButton btnSistemaProductos;
    private javax.swing.JButton btnSistemaUsusarios;
    private javax.swing.JButton btnSistemaVentas;
    private javax.swing.JPanel cn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblSistemaTitulo;
    private javax.swing.JMenuItem menuBitacoras;
    private javax.swing.JMenuItem menuCerrarS;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JMenuItem menuUsuarios;
    private javax.swing.JMenuItem menuVentas;
    // End of variables declaration//GEN-END:variables

}
